# Generated by Django 5.0.6 on 2024-07-06 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgement', '0003_problem_added_solution_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='test_file',
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_file_text', models.TextField()),
                ('test_description', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judgement.problem')),
            ],
        ),
    ]
