# Generated by Django 5.0.6 on 2024-07-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgement', '0005_test_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='cmp_file_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='tst_file_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
