# Generated by Django 5.0.6 on 2024-07-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgement', '0006_problem_cmp_file_text_problem_tst_file_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='timeout_cycles',
            field=models.PositiveIntegerField(default=0, help_text='The max number of cycles you students have to run your entire test code. 0 is infinite (Python will time out the CPU Emulator after 30 seconds).'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(default='Problem description.\n                                   \nInputs\nRAM[0] = 12\nRAM[1] = 12\n                                    \nOutputs\nRAM[2] = 12\n'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='tst_file_text',
            field=models.TextField(default='//NOTE: You may load this file as a .tst into your simulator to help debug your code.\nload assembly.hack,\noutput-file assembly.out,\ncompare-to compare.cmp,\n'),
        ),
    ]
